// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace RealsenseHandML.Model
{
    public class ModelInput
    {
        [ColumnName("R_Thumb_flexion"), LoadColumn(0)]
        public float R_Thumb_flexion { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_tip_w"), LoadColumn(1)]
        public float R_Rot_Thumb_tip_w { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_tip_x"), LoadColumn(2)]
        public float R_Rot_Thumb_tip_x { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_tip_y"), LoadColumn(3)]
        public float R_Rot_Thumb_tip_y { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_tip_z"), LoadColumn(4)]
        public float R_Rot_Thumb_tip_z { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt2_w"), LoadColumn(5)]
        public float R_Rot_Thumb_jt2_w { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt2_x"), LoadColumn(6)]
        public float R_Rot_Thumb_jt2_x { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt2_y"), LoadColumn(7)]
        public float R_Rot_Thumb_jt2_y { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt2_z"), LoadColumn(8)]
        public float R_Rot_Thumb_jt2_z { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt1_w"), LoadColumn(9)]
        public float R_Rot_Thumb_jt1_w { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt1_x"), LoadColumn(10)]
        public float R_Rot_Thumb_jt1_x { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt1_y"), LoadColumn(11)]
        public float R_Rot_Thumb_jt1_y { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_jt1_z"), LoadColumn(12)]
        public float R_Rot_Thumb_jt1_z { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_base_w"), LoadColumn(13)]
        public float R_Rot_Thumb_base_w { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_base_x"), LoadColumn(14)]
        public float R_Rot_Thumb_base_x { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_base_y"), LoadColumn(15)]
        public float R_Rot_Thumb_base_y { get; set; } = 0;


        [ColumnName("R_Rot_Thumb_base_z"), LoadColumn(16)]
        public float R_Rot_Thumb_base_z { get; set; } = 0;


        [ColumnName("R_Index_flexion"), LoadColumn(17)]
        public float R_Index_flexion { get; set; } = 0;


        [ColumnName("R_Rot_Index_tip_w"), LoadColumn(18)]
        public float R_Rot_Index_tip_w { get; set; } = 0;


        [ColumnName("R_Rot_Index_tip_x"), LoadColumn(19)]
        public float R_Rot_Index_tip_x { get; set; } = 0;


        [ColumnName("R_Rot_Index_tip_y"), LoadColumn(20)]
        public float R_Rot_Index_tip_y { get; set; } = 0;


        [ColumnName("R_Rot_Index_tip_z"), LoadColumn(21)]
        public float R_Rot_Index_tip_z { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt2_w"), LoadColumn(22)]
        public float R_Rot_Index_jt2_w { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt2_x"), LoadColumn(23)]
        public float R_Rot_Index_jt2_x { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt2_y"), LoadColumn(24)]
        public float R_Rot_Index_jt2_y { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt2_z"), LoadColumn(25)]
        public float R_Rot_Index_jt2_z { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt1_w"), LoadColumn(26)]
        public float R_Rot_Index_jt1_w { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt1_x"), LoadColumn(27)]
        public float R_Rot_Index_jt1_x { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt1_y"), LoadColumn(28)]
        public float R_Rot_Index_jt1_y { get; set; } = 0;


        [ColumnName("R_Rot_Index_jt1_z"), LoadColumn(29)]
        public float R_Rot_Index_jt1_z { get; set; } = 0;


        [ColumnName("R_Rot_Index_base_w"), LoadColumn(30)]
        public float R_Rot_Index_base_w { get; set; } = 0;


        [ColumnName("R_Rot_Index_base_x"), LoadColumn(31)]
        public float R_Rot_Index_base_x { get; set; } = 0;


        [ColumnName("R_Rot_Index_base_y"), LoadColumn(32)]
        public float R_Rot_Index_base_y { get; set; } = 0;


        [ColumnName("R_Rot_Index_base_z"), LoadColumn(33)]
        public float R_Rot_Index_base_z { get; set; } = 0;


        [ColumnName("R_Middle_flexion"), LoadColumn(34)]
        public float R_Middle_flexion { get; set; } = 0;


        [ColumnName("R_Rot_Middle_tip_w"), LoadColumn(35)]
        public float R_Rot_Middle_tip_w { get; set; } = 0;


        [ColumnName("R_Rot_Middle_tip_x"), LoadColumn(36)]
        public float R_Rot_Middle_tip_x { get; set; } = 0;


        [ColumnName("R_Rot_Middle_tip_y"), LoadColumn(37)]
        public float R_Rot_Middle_tip_y { get; set; } = 0;


        [ColumnName("R_Rot_Middle_tip_z"), LoadColumn(38)]
        public float R_Rot_Middle_tip_z { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt2_w"), LoadColumn(39)]
        public float R_Rot_Middle_jt2_w { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt2_x"), LoadColumn(40)]
        public float R_Rot_Middle_jt2_x { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt2_y"), LoadColumn(41)]
        public float R_Rot_Middle_jt2_y { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt2_z"), LoadColumn(42)]
        public float R_Rot_Middle_jt2_z { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt1_w"), LoadColumn(43)]
        public float R_Rot_Middle_jt1_w { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt1_x"), LoadColumn(44)]
        public float R_Rot_Middle_jt1_x { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt1_y"), LoadColumn(45)]
        public float R_Rot_Middle_jt1_y { get; set; } = 0;


        [ColumnName("R_Rot_Middle_jt1_z"), LoadColumn(46)]
        public float R_Rot_Middle_jt1_z { get; set; } = 0;


        [ColumnName("R_Rot_Middle_base_w"), LoadColumn(47)]
        public float R_Rot_Middle_base_w { get; set; } = 0;


        [ColumnName("R_Rot_Middle_base_x"), LoadColumn(48)]
        public float R_Rot_Middle_base_x { get; set; } = 0;


        [ColumnName("R_Rot_Middle_base_y"), LoadColumn(49)]
        public float R_Rot_Middle_base_y { get; set; } = 0;


        [ColumnName("R_Rot_Middle_base_z"), LoadColumn(50)]
        public float R_Rot_Middle_base_z { get; set; } = 0;


        [ColumnName("R_Ring_flexion"), LoadColumn(51)]
        public float R_Ring_flexion { get; set; } = 0;


        [ColumnName("R_Rot_Ring_tip_w"), LoadColumn(52)]
        public float R_Rot_Ring_tip_w { get; set; } = 0;


        [ColumnName("R_Rot_Ring_tip_x"), LoadColumn(53)]
        public float R_Rot_Ring_tip_x { get; set; } = 0;


        [ColumnName("R_Rot_Ring_tip_y"), LoadColumn(54)]
        public float R_Rot_Ring_tip_y { get; set; } = 0;


        [ColumnName("R_Rot_Ring_tip_z"), LoadColumn(55)]
        public float R_Rot_Ring_tip_z { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt2_w"), LoadColumn(56)]
        public float R_Rot_Ring_jt2_w { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt2_x"), LoadColumn(57)]
        public float R_Rot_Ring_jt2_x { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt2_y"), LoadColumn(58)]
        public float R_Rot_Ring_jt2_y { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt2_z"), LoadColumn(59)]
        public float R_Rot_Ring_jt2_z { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt1_w"), LoadColumn(60)]
        public float R_Rot_Ring_jt1_w { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt1_x"), LoadColumn(61)]
        public float R_Rot_Ring_jt1_x { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt1_y"), LoadColumn(62)]
        public float R_Rot_Ring_jt1_y { get; set; } = 0;


        [ColumnName("R_Rot_Ring_jt1_z"), LoadColumn(63)]
        public float R_Rot_Ring_jt1_z { get; set; } = 0;


        [ColumnName("R_Rot_Ring_base_w"), LoadColumn(64)]
        public float R_Rot_Ring_base_w { get; set; } = 0;


        [ColumnName("R_Rot_Ring_base_x"), LoadColumn(65)]
        public float R_Rot_Ring_base_x { get; set; } = 0;


        [ColumnName("R_Rot_Ring_base_y"), LoadColumn(66)]
        public float R_Rot_Ring_base_y { get; set; } = 0;


        [ColumnName("R_Rot_Ring_base_z"), LoadColumn(67)]
        public float R_Rot_Ring_base_z { get; set; } = 0;


        [ColumnName("R_Pingky_flexion"), LoadColumn(68)]
        public float R_Pingky_flexion { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_tip_w"), LoadColumn(69)]
        public float R_Rot_Pingky_tip_w { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_tip_x"), LoadColumn(70)]
        public float R_Rot_Pingky_tip_x { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_tip_y"), LoadColumn(71)]
        public float R_Rot_Pingky_tip_y { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_tip_z"), LoadColumn(72)]
        public float R_Rot_Pingky_tip_z { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt2_w"), LoadColumn(73)]
        public float R_Rot_Pingky_jt2_w { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt2_x"), LoadColumn(74)]
        public float R_Rot_Pingky_jt2_x { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt2_y"), LoadColumn(75)]
        public float R_Rot_Pingky_jt2_y { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt2_z"), LoadColumn(76)]
        public float R_Rot_Pingky_jt2_z { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt1_w"), LoadColumn(77)]
        public float R_Rot_Pingky_jt1_w { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt1_x"), LoadColumn(78)]
        public float R_Rot_Pingky_jt1_x { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt1_y"), LoadColumn(79)]
        public float R_Rot_Pingky_jt1_y { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_jt1_z"), LoadColumn(80)]
        public float R_Rot_Pingky_jt1_z { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_base_w"), LoadColumn(81)]
        public float R_Rot_Pingky_base_w { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_base_x"), LoadColumn(82)]
        public float R_Rot_Pingky_base_x { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_base_y"), LoadColumn(83)]
        public float R_Rot_Pingky_base_y { get; set; } = 0;


        [ColumnName("R_Rot_Pingky_base_z"), LoadColumn(84)]
        public float R_Rot_Pingky_base_z { get; set; } = 0;


        [ColumnName("L_Thumb_flexion"), LoadColumn(85)]
        public float L_Thumb_flexion { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_tip_w"), LoadColumn(86)]
        public float L_Rot_Thumb_tip_w { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_tip_x"), LoadColumn(87)]
        public float L_Rot_Thumb_tip_x { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_tip_y"), LoadColumn(88)]
        public float L_Rot_Thumb_tip_y { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_tip_z"), LoadColumn(89)]
        public float L_Rot_Thumb_tip_z { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt2_w"), LoadColumn(90)]
        public float L_Rot_Thumb_jt2_w { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt2_x"), LoadColumn(91)]
        public float L_Rot_Thumb_jt2_x { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt2_y"), LoadColumn(92)]
        public float L_Rot_Thumb_jt2_y { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt2_z"), LoadColumn(93)]
        public float L_Rot_Thumb_jt2_z { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt1_w"), LoadColumn(94)]
        public float L_Rot_Thumb_jt1_w { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt1_x"), LoadColumn(95)]
        public float L_Rot_Thumb_jt1_x { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt1_y"), LoadColumn(96)]
        public float L_Rot_Thumb_jt1_y { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_jt1_z"), LoadColumn(97)]
        public float L_Rot_Thumb_jt1_z { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_base_w"), LoadColumn(98)]
        public float L_Rot_Thumb_base_w { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_base_x"), LoadColumn(99)]
        public float L_Rot_Thumb_base_x { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_base_y"), LoadColumn(100)]
        public float L_Rot_Thumb_base_y { get; set; } = 0;


        [ColumnName("L_Rot_Thumb_base_z"), LoadColumn(101)]
        public float L_Rot_Thumb_base_z { get; set; } = 0;


        [ColumnName("L_Index_flexion"), LoadColumn(102)]
        public float L_Index_flexion { get; set; } = 0;


        [ColumnName("L_Rot_Index_tip_w"), LoadColumn(103)]
        public float L_Rot_Index_tip_w { get; set; } = 0;


        [ColumnName("L_Rot_Index_tip_x"), LoadColumn(104)]
        public float L_Rot_Index_tip_x { get; set; } = 0;


        [ColumnName("L_Rot_Index_tip_y"), LoadColumn(105)]
        public float L_Rot_Index_tip_y { get; set; } = 0;


        [ColumnName("L_Rot_Index_tip_z"), LoadColumn(106)]
        public float L_Rot_Index_tip_z { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt2_w"), LoadColumn(107)]
        public float L_Rot_Index_jt2_w { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt2_x"), LoadColumn(108)]
        public float L_Rot_Index_jt2_x { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt2_y"), LoadColumn(109)]
        public float L_Rot_Index_jt2_y { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt2_z"), LoadColumn(110)]
        public float L_Rot_Index_jt2_z { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt1_w"), LoadColumn(111)]
        public float L_Rot_Index_jt1_w { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt1_x"), LoadColumn(112)]
        public float L_Rot_Index_jt1_x { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt1_y"), LoadColumn(113)]
        public float L_Rot_Index_jt1_y { get; set; } = 0;


        [ColumnName("L_Rot_Index_jt1_z"), LoadColumn(114)]
        public float L_Rot_Index_jt1_z { get; set; } = 0;


        [ColumnName("L_Rot_Index_base_w"), LoadColumn(115)]
        public float L_Rot_Index_base_w { get; set; } = 0;


        [ColumnName("L_Rot_Index_base_x"), LoadColumn(116)]
        public float L_Rot_Index_base_x { get; set; } = 0;


        [ColumnName("L_Rot_Index_base_y"), LoadColumn(117)]
        public float L_Rot_Index_base_y { get; set; } = 0;


        [ColumnName("L_Rot_Index_base_z"), LoadColumn(118)]
        public float L_Rot_Index_base_z { get; set; } = 0;


        [ColumnName("L_Middle_flexion"), LoadColumn(119)]
        public float L_Middle_flexion { get; set; } = 0;


        [ColumnName("L_Rot_Middle_tip_w"), LoadColumn(120)]
        public float L_Rot_Middle_tip_w { get; set; } = 0;


        [ColumnName("L_Rot_Middle_tip_x"), LoadColumn(121)]
        public float L_Rot_Middle_tip_x { get; set; } = 0;


        [ColumnName("L_Rot_Middle_tip_y"), LoadColumn(122)]
        public float L_Rot_Middle_tip_y { get; set; } = 0;


        [ColumnName("L_Rot_Middle_tip_z"), LoadColumn(123)]
        public float L_Rot_Middle_tip_z { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt2_w"), LoadColumn(124)]
        public float L_Rot_Middle_jt2_w { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt2_x"), LoadColumn(125)]
        public float L_Rot_Middle_jt2_x { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt2_y"), LoadColumn(126)]
        public float L_Rot_Middle_jt2_y { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt2_z"), LoadColumn(127)]
        public float L_Rot_Middle_jt2_z { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt1_w"), LoadColumn(128)]
        public float L_Rot_Middle_jt1_w { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt1_x"), LoadColumn(129)]
        public float L_Rot_Middle_jt1_x { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt1_y"), LoadColumn(130)]
        public float L_Rot_Middle_jt1_y { get; set; } = 0;


        [ColumnName("L_Rot_Middle_jt1_z"), LoadColumn(131)]
        public float L_Rot_Middle_jt1_z { get; set; } = 0;


        [ColumnName("L_Rot_Middle_base_w"), LoadColumn(132)]
        public float L_Rot_Middle_base_w { get; set; } = 0;


        [ColumnName("L_Rot_Middle_base_x"), LoadColumn(133)]
        public float L_Rot_Middle_base_x { get; set; } = 0;


        [ColumnName("L_Rot_Middle_base_y"), LoadColumn(134)]
        public float L_Rot_Middle_base_y { get; set; } = 0;


        [ColumnName("L_Rot_Middle_base_z"), LoadColumn(135)]
        public float L_Rot_Middle_base_z { get; set; } = 0;


        [ColumnName("L_Ring_flexion"), LoadColumn(136)]
        public float L_Ring_flexion { get; set; } = 0;


        [ColumnName("L_Rot_Ring_tip_w"), LoadColumn(137)]
        public float L_Rot_Ring_tip_w { get; set; } = 0;


        [ColumnName("L_Rot_Ring_tip_x"), LoadColumn(138)]
        public float L_Rot_Ring_tip_x { get; set; } = 0;


        [ColumnName("L_Rot_Ring_tip_y"), LoadColumn(139)]
        public float L_Rot_Ring_tip_y { get; set; } = 0;


        [ColumnName("L_Rot_Ring_tip_z"), LoadColumn(140)]
        public float L_Rot_Ring_tip_z { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt2_w"), LoadColumn(141)]
        public float L_Rot_Ring_jt2_w { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt2_x"), LoadColumn(142)]
        public float L_Rot_Ring_jt2_x { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt2_y"), LoadColumn(143)]
        public float L_Rot_Ring_jt2_y { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt2_z"), LoadColumn(144)]
        public float L_Rot_Ring_jt2_z { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt1_w"), LoadColumn(145)]
        public float L_Rot_Ring_jt1_w { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt1_x"), LoadColumn(146)]
        public float L_Rot_Ring_jt1_x { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt1_y"), LoadColumn(147)]
        public float L_Rot_Ring_jt1_y { get; set; } = 0;


        [ColumnName("L_Rot_Ring_jt1_z"), LoadColumn(148)]
        public float L_Rot_Ring_jt1_z { get; set; } = 0;


        [ColumnName("L_Rot_Ring_base_w"), LoadColumn(149)]
        public float L_Rot_Ring_base_w { get; set; } = 0;


        [ColumnName("L_Rot_Ring_base_x"), LoadColumn(150)]
        public float L_Rot_Ring_base_x { get; set; } = 0;


        [ColumnName("L_Rot_Ring_base_y"), LoadColumn(151)]
        public float L_Rot_Ring_base_y { get; set; } = 0;


        [ColumnName("L_Rot_Ring_base_z"), LoadColumn(152)]
        public float L_Rot_Ring_base_z { get; set; } = 0;


        [ColumnName("L_Pingky_flexion"), LoadColumn(153)]
        public float L_Pingky_flexion { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_tip_w"), LoadColumn(154)]
        public float L_Rot_Pingky_tip_w { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_tip_x"), LoadColumn(155)]
        public float L_Rot_Pingky_tip_x { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_tip_y"), LoadColumn(156)]
        public float L_Rot_Pingky_tip_y { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_tip_z"), LoadColumn(157)]
        public float L_Rot_Pingky_tip_z { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt2_w"), LoadColumn(158)]
        public float L_Rot_Pingky_jt2_w { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt2_x"), LoadColumn(159)]
        public float L_Rot_Pingky_jt2_x { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt2_y"), LoadColumn(160)]
        public float L_Rot_Pingky_jt2_y { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt2_z"), LoadColumn(161)]
        public float L_Rot_Pingky_jt2_z { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt1_w"), LoadColumn(162)]
        public float L_Rot_Pingky_jt1_w { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt1_x"), LoadColumn(163)]
        public float L_Rot_Pingky_jt1_x { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt1_y"), LoadColumn(164)]
        public float L_Rot_Pingky_jt1_y { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_jt1_z"), LoadColumn(165)]
        public float L_Rot_Pingky_jt1_z { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_base_w"), LoadColumn(166)]
        public float L_Rot_Pingky_base_w { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_base_x"), LoadColumn(167)]
        public float L_Rot_Pingky_base_x { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_base_y"), LoadColumn(168)]
        public float L_Rot_Pingky_base_y { get; set; } = 0;


        [ColumnName("L_Rot_Pingky_base_z"), LoadColumn(169)]
        public float L_Rot_Pingky_base_z { get; set; } = 0;


        [ColumnName("label"), LoadColumn(170)]
        public string Label { get; set; } 


    } 
} 
